name: agendamentos_web
description: App Flutter Web para agendamentos com Firebase
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  intl: ^0.19.0

  # NecessÃ¡rio para Flutter Web funcionar
  firebase_auth_web: ^5.8.9
  firebase_core_web: ^2.17.1

flutter:
  uses-material-design: true

